### ISSUE TITLE
Contruir o Fluxograma com base no wireframe

### ISSUE THREAD

**Issue by Michel-Momose** [InfinityDevAPI/InfintyDev#4]

**Comment by ropcastr** [comment]
Feito primeiro modelo de fluxograma do aplicativo e upado para a pasta Documentos do repositório

**Comment by ropcastr** [comment]
Falta agora terminar as telas em conjunto com o @VonNexx

**Comment by VonNexx** [comment]
Primeira implementação do fluxograma das telas para o Figma, faltando apenas as telas de Relatórios.

https://www.figma.com/file/pHK9hmlxfVfxWMvj89RqEe/Infinity-Dev?type=design&node-id=0%3A1&mode=design&t=T2YMmp2FAbJ7CHd5-1

**Comment by ropcastr** [comment]
Realizado o upload da versão revisada do fluxograma de acordo com as mudanças feitas na última reunião para discutir o wireframe
