### ISSUE TITLE
Modelagem do Banco de dados

### ISSUE THREAD

**Issue by Michel-Momose** [InfinityDevAPI/InfintyDev#5]

**Comment by Michel-Momose** [comment]
Implementar o Modelo Entidade-Relacionamento (MER) e o criar um Diagrama Entidade Relacionamento.

**Comment by Michel-Momose** [comment]
# Esboço do MER:

## Entidades Principais:

### a. Aluno

- ID (chave primaria)
- Nome 
- Email informado
- Email fatec (se diferente do informado) (relação 1,1)
- Matriculado em (TG1 e/ou TG2)
-

### b. Orientador

- Nome
- Email Fatec (chave primaria)

### c. Trabalho de Graduação (TG)

- ID (Chave Primária)
- Tipo do TG
- Problema a ser tratado
- Status (em andamento, concluído, etc.)
- Data de início
- Data de conclusão prevista
- Empresa envolvida
- Disciplina

### d. Entrega do TG

- ID (Chave Primária)
- ID do TG (Chave Estrangeira para relacionar com o TG correspondente)
- Data da entrega
- Descrição da atividade
- Nota atribuída
- Feedback do professor

## Relacionamentos:

> Cada Aluno pode estar associado a apenas um TG (relacionamento 1 para 1 entre Aluno e TG).
> Cada Orientador pode orientar vários TGs, mas um TG é orientado por apenas um Orientador (relacionamento 1 para N entre Orientador e TG).
> Cada TG pode ter várias entregas, e cada entrega está associada a apenas um TG (relacionamento 1 para N entre TG e Entrega).

**Comment by ropcastr** [comment]
Caros, com base na modelagem que fizeram e nas entidades de relacionamento, criei um diagrama de classes para o projeto e fiz upload do mesmo para a pasta documentação. Sintam-se livres para revisar e propor alterações que possam ajudar no desenvolvimento.

**Comment by Michel-Momose** [comment]
Modelagem de Dados, MER, modelo lógico e conceitual e diagrama de classes finalizado com sucesso.
